server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://43.155.176.239:3306/dujiangyan
    username: dujiangyan
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    # Exclude automatic configuration
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
    # 31 days
    timeout: 2678400